name: 📙 Terminal template
description: |
  A template mimicking a SSH session.
examples:
  default: https://github.com/lowlighter/metrics/blob/examples/metrics.terminal.svg
index: 2
supports:
  - user
  - organization
formats:
  - svg
  - png
  - jpeg
  - json
